<!DOCTYPE html>
<html>
<head>
<title>Match Report - {{ $match->title }}</title>
<style>
body{font-family:Helvetica,Arial,sans-serif;font-size:12px;color:#333;margin:0;padding:20px;}
.header{text-align:center;margin-bottom:30px;padding-bottom:10px;border-bottom:2px solid #ea580c;}
.header h2{margin:0 0 5px 0;color:#1e293b;font-size:24px;text-transform:uppercase;}
.header p{margin:0;color:#64748b;font-size:14px;}
table{width:100%;border-collapse:collapse;margin-top:20px;}
th,td{border:1px solid #e2e8f0;padding:10px;text-align:center;}
th{background-color:#f8fafc;color:#475569;font-weight:bold;text-transform:uppercase;font-size:11px;}
td.left-align{text-align:left;}
.player-name{font-weight:bold;color:#0f172a;}
.footer{margin-top:40px;text-align:right;font-size:10px;color:#94a3b8;}
</style>
</head>
<body>
<div class="header">
<h2>MATCH REPORT</h2>
<p>{{ $match->title }} | {{ \Carbon\Carbon::parse($match->match_date)->format('d F Y') }}</p>
</div>
<table>
<thead>
<tr>
<th class="left-align">Player</th>
<th>No.</th>
<th>Position</th>
<th>Goals</th>
<th>Assists</th>
<th>Shots on Target</th>
<th>Succ. Passes</th>
</tr>
</thead>
<tbody>
@foreach($match->players as $player)
<tr>
<td class="left-align player-name">{{ $player->name }}</td>
<td>{{ $player->jersey_number ?? '-' }}</td>
<td>{{ $player->pivot->position }}</td>
<td>{{ $stats[$player->id]->total_goals ?? 0 }}</td>
<td>{{ $stats[$player->id]->total_assists ?? 0 }}</td>
<td>{{ $stats[$player->id]->total_shots_target ?? 0 }}</td>
<td>{{ $stats[$player->id]->total_passes ?? 0 }}</td>
</tr>
@endforeach
</tbody>
</table>
<div class="footer">
Generated by FFA Analytics Pro Suite - {{ now()->format('Y-m-d H:i:s') }}
</div>
</body>
</html>